#!/bin/bash
#SBATCH -t 10:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=2

# Go to home folder
# Vraag: is workdir gelijk aan de huidige subdirectory waarin ik zit??
cd $HOME/workdir

# Copy ini and py files, and executable to scratch
cp *.ini $TMPDIR
cp *.py $TMPDIR
# Vraag: kopieer ik op deze manier correct de executable, of kan ik beter een symbolische link aanmaken?
cp ./microhh $TMPDIR

# Go to scratch space
cd $TMPDIR

# Do the initialisation
srun ./microhh init

# Do the run
srun ./microhh run

# At finish, copy some files back to home
cp *.out $HOME/datadir
cp *.nc $HOME/datadir
